.\" Process this file with
.\" groff -man -Tascii tsh.1
.\"
.TH TSH 1 "OCTOBER 2013" Linux "User Manuals"
.SH NAME
tsh \- a tiny shell that mimics bash
.SH SYNOPSIS
.B ./tsh
.SH DESCRIPTION
.B tsh
mimics a Unix shell.  tsh has cd, exit, jobs, bg and fg as built-in commands.  tsh also handles I/O redirection,
 piped commands, and aliasing commands.  Jobs (both bg and fg) are stored in a linked list.  Aliases are also stored 
in a linked list.  
.SH FILES
.I /tsh.h,.c
.RS
Contains the program's 'main' function, which takes input from the user, interprets it, runs the appropriate command,
 and prints related output.
.RE
.I /interpreter.h,.c
.RS
Functions that handle interpretation of user input into the tiny shell.
.RE
.I /io.h,.c
.RS
Functions that handle input into and output from the tiny shell.
.RE
.I /runtime.h,.c
.RS
Functions that handle interpreted input from the shell and run the appropriate commands.
.RE
.I /jobs.h,.c
.RS
Functions that handle the addition, deletion, completion and checking of foreground and background jobs, traversing 
the linked list of same.
.RE
.I /alias.h,.c
.RS
Functions that handle fetching, adding, deleting, and printing aliases, traversing the linked list of same.
.RE
.I /pipes.h,.c
.RS
blabla
.SH BUGS
The command name should have been chosen more carefully
to reflect its purpose.
.SH AUTHORS
Alex Chambers, Audrey Hosford, Ben Rafshoon
